### ISSUE TITLE
Why does the pom file under the root directory start with f

### ISSUE THREAD

**Issue by shouldnotappearcalm** [quartzdesk/quartzdesk-executor#2]
Did you make a mistake when submitting the code?
![image](https://user-images.githubusercontent.com/20592210/73642045-eb583580-46ab-11ea-8519-1e35b7873189.png)

**Comment by xmoravej** [comment]
Fixed. Thank you for bringing this to our attention.

**Comment by shouldnotappearcalm** [comment]
You are welcome.
